# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f553dab803bb01e3348e810b24ce2c063afcbfa4cea3f566fd184e9e90daa346aabb9b60b3ca22abc018759bd98ef261654980bc1a4aef00bfd549b995dd6d2

test:
  secret_key_base: f8feba49a2d27e2b03d39b0c930d61ce57c26ba8e17c5197a422a608010481ec1cd193a77586d8f476f09aee10f9b6cbc7fa89de9f1b0f752b4f21b71f128caf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
